name: Build and Push

on:
  schedule:
    - cron:  '0 0 1 * *' # at 00:00 on 1st of month
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - context: "php-cli/php8.1"
            tags: ghcr.io/hoogi91/php-cli:8.1
          - context: "php-cli/php8.2"
            tags: |
              ghcr.io/hoogi91/php-cli:8.2
              ghcr.io/hoogi91/php-cli:latest
          - context: "php-nginx/php8.1"
            tags: ghcr.io/hoogi91/php-nginx:8.1
          - context: "php-nginx/php8.2"
            tags: |
              ghcr.io/hoogi91/php-nginx:8.2
              ghcr.io/hoogi91/php-nginx:latest
          - context: "typo3/php8.1"
            tags: ghcr.io/hoogi91/typo3/php:8.1
          - context: "typo3/php8.2"
            tags: |
              ghcr.io/hoogi91/typo3/php:8.2
              ghcr.io/hoogi91/typo3/php:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: '${{ matrix.context }}'
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max