name: PHP cli Build

on:
  schedule:
    - cron: '0 0 1 * *' # at 00:00 on 1st of month
  push:
    branches:
      - "main"
    paths:
      - "php-cli/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 8.1
            tags: ghcr.io/hoogi91/php-cli:8.1
          - version: 8.2
            tags: ghcr.io/hoogi91/php-cli:8.2
          - version: 8.3
            tags: |
              ghcr.io/hoogi91/php-cli:8.3
              ghcr.io/hoogi91/php-cli:latest
          # add newrelic builds
          - version: 8.1
            target: newrelic
            tags: ghcr.io/hoogi91/php-cli-newrelic:8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: 'php-cli'
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ matrix.tags }}
          target: ${{ matrix.target }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}-cli-bullseye
          cache-from: type=gha
          cache-to: type=gha,mode=max
